---

version: 2
updates:

  # Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@ch3ck"
    open-pull-requests-limit: 10

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@ch3ck"
    open-pull-requests-limit: 10
  
  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    reviewers:
      - "@ch3ck"
    open-pull-requests-limit: 10
