name: Security audits (Scorecards supply-chain security, Cargo audit)
on: 
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '42 12 * * 2'
  push:
    branches: [ master ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  run-security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
