# GitHub Actions workflow to deploy Lambda functions with RUST runtime
# Author: Nyah Check

name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run-security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run code audit fix
        run: cargo audit
      - name: Check style
        run: cargo +nightly fmt
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly, beta]
    steps:
    - uses: actions/checkout@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose