# Actions workflow to build code and run unit tests
# Author: Nyah Check
name: Build & Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: davidgraeff/rust-musl-action@master
    - uses: actions/checkout@master
    - name: Build and Test
      run: cargo test --target x86_64-unknown-linux-musl
