# Actions workflow to build code and run unit tests
# Author: Nyah Check
name: Build & Run Tests

on: [push, pull_request]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
