# GitHub Actions workflow to deploy Lambda functions with RUST runtime
# Author: Nyah Check

name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run-security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run code audit
        run: cargo audit
      - name: Check style
        run: cargo +nightly fmt --check
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly, beta]
    steps:
    - uses: actions/checkout@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        rust-version: stable
    - name: Build for release
      run: |
        cargo build -p lambda_runtime --example privatemail --release
        cp ./target/release/examples/privatemail ./bootstrap && zip lambda.zip bootstrap && rm bootstrap
    - name: Deploy Lambda
      if: github.ref == 'refs/heads/master'
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: private-email-service
        zip_file: example/lambda.zip
        memory_size: 128
        timeout: 30
        handler: privatemail_handler
        role: arn:aws:iam::${{secrets.AWS_ACCOUNT}}:role/SESEmailForwardToHey-SESEmailForwardRole-1A0JBVFNWVXLY
        runtime: provided
        environment: RUST_BACKTRACE=1
