# GitHub Actions workflow to create AWS resources for SES Lambda
# Author: Nyah Check
name: Package Code & Provision Infrastructure

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  terraform-infra-provisioning:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          rust-version: stable
      - name: Fetch musl-rust image
        run: docker pull clux/muslrust
      - name: Build rust release binary
        run: |
          rustup target add x86_64-unknown-linux-musl
          docker run -v $PWD:/volume --rm -t clux/muslrust cargo build --release --target x86_64-unknown-linux-musl
      - name: package lambda zip for terraform
        run: |
          zip -j lambda.zip ./target/x86_64-unknown-linux-musl/release/bootstrap
          cp lambda.zip terraform/
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        env:
          TF_VAR_from_email: ${{ secrets.TO_EMAIL }}
          TF_VAR_to_email: ${{ secrets.FROM_EMAIL }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check terraform
      - name: Terraform init
        id: init
        run: terraform init terraform
      - name: Terraform Validate
        id: validate
        run: terraform validate -json terraform
      - name: Terraform Plan
        run: terraform plan terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve terraform
